node {
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo()


  stage('GIT CheckOut') {
    git branch: 'production', url: 'https://github.com/ArunagiriS/DevOps.git'
	}

  def pr

  dioject_path = "ansible-code/03-Apache/"(project_path) {
	
	stage('Geting Ready For Ansible') {
		sh label: 'Jenkins', script: "echo '<html><h1> Welcome to DevOps Ansible Apache Deployment </h1><h3> TASK BUILD ID: ${env.BUILD_DISPLAY_NAME}</h3></html>' > files/index.html"
			}

	stage('soymenAnsible Apache Depl - PROD') { 
		label: '', script: 'ansible-playbook playbook.yaml'
        }

 }
	
 def project_terra="terrafrom-code/04-Tomcat-Deploy"
 
 dir(project_terra) {
	
	stage('Build Managment') {
		def downloadSpec = """{
			"files": [{
					"pattern": "Generic-Artifactory/*.war",
					"target": "ansible-code/05-Tomcat/files/"
				}]
			}"""
		server.download spec: downloadSpec
	}

 	stage('Prod Deployment on AWS'){
 		sh label: 'terraform', script: 'terraform  init'
   		sh label: 'terraform', script: 'terraform  apply -input=false -auto-approve'
   	}
 }
	

}
